import { PortfolioData } from '../models/portfolio.model';

export const PORTFOLIO_DATA: PortfolioData = {
    profile: {
        name: 'Emre Kart',
        title: 'Computer Engineer',
        tagline: 'Building Scalable SaaS Architectures & AI-Driven Solutions',
        subTagline: 'Computer Engineer specializing in .NET Core, Angular, and Cloud Native Technologies',
        location: 'Istanbul, Turkiye',
        email: 'kartemre3403@gmail.com',
        bio: `Passionate Computer Engineer with expertise in full-stack development, cloud architecture, and AI integration. 
    Experienced in building enterprise-grade SaaS platforms using .NET Core, Angular, and modern DevOps practices. 
    Dedicated to creating scalable, maintainable solutions that solve real-world problems.`,
        links: {
            github: 'https://github.com/kartemre',
            linkedin: 'https://www.linkedin.com/in/emre-kart',
            website: 'https://emrekart.me',
        },
    },

    education: [
        {
            id: 'edu-1',
            institution: 'Eskişehir Osmangazi University',
            degree: 'Bachelor of Science',
            field: 'Computer Engineering',
            location: 'Eskişehir, Turkiye',
            startDate: '2020-09',
            endDate: '2025-07',
            description: 'Comprehensive computer engineering curriculum covering software development, algorithms, system design, and artificial intelligence.',
        },
        {
            id: 'edu-2',
            institution: '42 Schools',
            degree: 'Peer-to-Peer Learning Program',
            field: 'Computer Science',
            location: 'Paris/Istanbul Network',
            startDate: '2025-05',
            endDate: 'Present',
            description: 'Intensive project-based learning program focusing on C/C++ programming, Unix systems, algorithms, and software engineering principles.',
        },
    ],

    experience: [
        {
            id: 'exp-1',
            title: 'Software Development Intern',
            company: 'BosphorusISS',
            location: 'Istanbul, Turkiye',
            type: 'internship',
            startDate: '2025-07',
            endDate: '2025-07',
            current: false,
            description: 'Architected and developed a real-time task management system utilizing cutting-edge distributed technologies.',
            technologies: ['.NET 8', 'ASP.NET Core', 'SignalR', 'RabbitMQ', 'Redis', 'PostgreSQL', 'Clean Architecture'],
            achievements: [
                'Implemented real-time collaboration features using SignalR for instant task updates',
                'Designed message queue system with RabbitMQ for asynchronous processing',
                'Optimized performance using Redis caching, reducing database queries by 60%',
                'Applied Clean Architecture principles for maintainable, testable codebase',
            ],
        },
        {
            id: 'exp-2',
            title: 'R&D Product Development Intern',
            company: 'Sovos',
            location: 'Istanbul, Turkiye',
            type: 'internship',
            startDate: '2024-12',
            endDate: '2025-04',
            current: false,
            description: 'Developed a modular AI-powered tax compliance assistant chatbot that can be easily integrated into existing platforms.',
            technologies: ['ASP.NET Core', 'Angular', 'Python', 'RAG (Retrieval-Augmented Generation)', 'Web Scraping', 'N-Tier Architecture', 'AI/LLM'],
            achievements: [
                'Designed and implemented RAG (Retrieval-Augmented Generation) architecture for high-accuracy responses to complex tax regulation queries',
                'Built sector-specific dataset through web scraping of Turkish Revenue Administration (GİB) data',
                'Developed backend using ASP.NET Core with N-Tier Architecture principles',
                'Created frontend interface with Angular for seamless user experience',
                'Delivered working prototype ready for integration into Sovos product family',
            ],
        },
        {
            id: 'exp-3',
            title: 'Software Developer Intern',
            company: 'TCM Bilisim',
            location: 'Istanbul, Turkiye',
            type: 'internship',
            startDate: '2024-07',
            endDate: '2024-12',
            current: false,
            description: 'Developed custom enterprise applications using Microsoft technologies and low-code platforms.',
            technologies: ['.NET MVC', 'ASP.NET Core API', 'Power Platform', 'Microsoft Dynamics', 'SQL Server'],
            achievements: [
                'Built custom business applications using .NET MVC framework',
                'Designed and implemented RESTful APIs for enterprise integrations',
                'Automated business processes using Power Automate and Power Apps',
                'Enhanced existing applications with new features and performance improvements',
            ],
        },
        {
            id: 'exp-4',
            title: 'Researcher - STAR Program',
            company: 'TUBITAK (The Scientific and Technological Research Council of Turkey)',
            location: 'Turkiye',
            type: 'contract',
            startDate: '2024-02',
            endDate: '2024-12',
            current: false,
            description: 'Conducted research on AI-based numerology allocation algorithms for next-generation 6G wireless networks.',
            technologies: ['Python', 'Machine Learning', 'TensorFlow', 'Scikit-learn', 'ANN', 'KNN', 'Random Forest'],
            achievements: [
                'Developed machine learning models for intelligent resource allocation in 6G networks',
                'Implemented and compared ANN, KNN, and Random Forest algorithms',
                'Published research findings and contributed to academic publications',
                'Optimized algorithm performance achieving 92% accuracy in predictions',
            ],
        },
        {
            id: 'exp-5',
            title: 'Vehicle Control and Telemetry System Team Leader',
            company: 'Mavera Tech Team',
            location: 'Eskişehir, Turkiye',
            type: 'part-time',
            startDate: '2024-09',
            endDate: '2025-01',
            current: false,
            description: 'Led the vehicle control and telemetry system unit in the electric vehicle team.',
            technologies: ['Embedded C', 'C++', 'Microcontrollers', 'CAN Bus', 'Real-time Systems', 'Telemetry'],
            achievements: [
                'Led vehicle control system and telemetry development team',
                'Participated in Teknofest 2024 Efficiency Challenge',
                'Coordinated integration of control algorithms and telemetry data collection',
                'Managed team workflow and technical decision-making',
            ],
        },
        {
            id: 'exp-6',
            title: 'Vehicle Control and Telemetry System Team Member',
            company: 'Mavera Tech Team',
            location: 'Eskişehir, Turkiye',
            type: 'part-time',
            startDate: '2023-07',
            endDate: '2024-08',
            current: false,
            description: 'Worked on vehicle control systems and telemetry systems in the electric vehicle team.',
            technologies: ['Embedded C', 'C++', 'Microcontrollers', 'CAN Bus', 'Real-time Systems'],
            achievements: [
                'Developed vehicle control system components',
                'Implemented telemetry data collection and monitoring',
                'Collaborated on integration of motor control and battery management systems',
            ],
        },
    ],

    projects: [
        {
            id: 'proj-1',
            title: 'Randevu Bulurum',
            description: 'Enterprise-grade SaaS appointment management platform serving thousands of users',
            longDescription: `A comprehensive appointment management system designed for businesses of all sizes. 
      Features include real-time booking, automated notifications, calendar integration, and detailed analytics. 
      Built with scalability and reliability as core principles, deployed on production infrastructure with 
      containerized microservices architecture.`,
            technologies: [
                '.NET 8',
                'ASP.NET Core',
                'CQRS Pattern',
                'Onion Architecture',
                'Next.js 14',
                'React',
                'TypeScript',
                'PostgreSQL',
                'Docker',
                'Nginx',
                'Let\'s Encrypt SSL',
                'Linux Server Management',
            ],
            liveUrl: 'https://randevubulurum.com',
            featured: true,
            category: 'web',
            achievements: [
                'Architected full-stack SaaS platform from concept to production',
                'Implemented CQRS and Onion Architecture for clean separation of concerns',
                'Containerized entire application using Docker for easy deployment',
                'Configured production server with Nginx reverse proxy and SSL certificates',
                'Managing live production environment with zero downtime deployments',
            ],
        },
        {
            id: 'proj-2',
            title: 'Multimodal Meme Classification System',
            description: 'AI-powered content analysis platform using vision transformers and CLIP models',
            longDescription: `Advanced machine learning system for analyzing and classifying meme content using 
      multimodal AI models. Combines image and text understanding through CLIP and Vision Transformer architectures. 
      Features include sentiment analysis, category classification, and real-time inference.`,
            technologies: [
                '.NET 8',
                'ASP.NET Core API',
                'Python',
                'FastAPI',
                'PyTorch',
                'CLIP Model',
                'Vision Transformers (ViT)',
                'Angular 16',
                'Chart.js',
                'Docker',
            ],
            sourceUrl: 'https://github.com/kartemre/multimodal-meme-classification-interface',
            featured: true,
            category: 'ai',
            achievements: [
                'Integrated state-of-the-art CLIP and ViT models for multimodal understanding',
                'Built Python microservice with FastAPI for ML inference',
                '.NET Core backend for orchestration and data management',
                'Angular frontend with interactive visualizations using Chart.js',
                'Achieved 89% classification accuracy on test dataset',
            ],
        },
        {
            id: 'proj-3',
            title: 'T-BOT: Banking AI Assistant',
            description: 'Context-aware conversational AI for banking customer support',
            longDescription: `Intelligent chatbot leveraging Large Language Models for banking customer service. 
      Features include natural language understanding, transaction queries, account management assistance, 
      and secure user authentication. Utilizes vector databases for efficient context retrieval.`,
            technologies: [
                'Python',
                'FastAPI',
                'LangChain',
                'OpenAI GPT',
                'Vector Database (Pinecone)',
                'Angular',
                'WebSockets',
                'JWT Authentication',
            ],
            sourceUrl: 'https://github.com/kartemre/TEB-ICAT-CIKAR',
            featured: true,
            category: 'ai',
            achievements: [
                'Implemented RAG (Retrieval-Augmented Generation) for accurate responses',
                'Designed conversation flow with context management',
                'Integrated secure authentication and session handling',
                'Built real-time chat interface with WebSocket communication',
            ],
        },
        {
            id: 'proj-4',
            title: 'EcoWater Platform',
            description: 'Hackathon-winning sustainable water consumption tracking platform',
            longDescription: `Web application promoting sustainable water usage through gamification and analytics. 
      Users can track their consumption, set goals, earn badges, and compare with community averages. 
      Won first place at university hackathon.`,
            technologies: ['Python', 'Django', 'PostgreSQL', 'Bootstrap', 'Chart.js', 'REST API'],
            sourceUrl: 'https://github.com/kartemre/Hackathon',
            featured: false,
            category: 'web',
            achievements: [
                '🏆 First Place Winner - University Hackathon 2024',
                'Developed full-stack application in 48 hours',
                'Implemented gamification system to encourage water conservation',
                'Created data visualization dashboard for consumption analytics',
            ],
        },
        {
            id: 'proj-5',
            title: 'Task Management API',
            description: 'RESTful API for team collaboration and project management',
            technologies: ['.NET 8', 'Entity Framework Core', 'PostgreSQL', 'JWT', 'Swagger', 'Clean Architecture'],
            featured: false,
            category: 'web',
        },
        {
            id: 'proj-6',
            title: 'Portfolio Website',
            description: 'Modern, responsive portfolio built with Angular and Tailwind CSS',
            technologies: ['Angular 18', 'TypeScript', 'Tailwind CSS', 'RxJS', 'GitHub Pages'],
            liveUrl: 'https://emrekart.me',
            featured: false,
            category: 'web',
        },
    ],

    skillCategories: [
        {
            name: 'Backend Development',
            icon: 'fa-server',
            skills: [
                { name: 'RESTful APIs', level: 85, category: 'Backend Development', icon: 'fa-exchange-alt' },
                { name: '.NET 8 / ASP.NET Core', level: 85, category: 'Backend Development', icon: 'devicon-dotnetcore-plain' },
                { name: 'C#', level: 85, category: 'Backend Development', icon: 'devicon-csharp-plain' },
            ],
        },
        {
            name: 'Frontend Development',
            icon: 'fa-palette',
            skills: [
                { name: 'HTML5 / CSS3', level: 85, category: 'Frontend Development', icon: 'devicon-html5-plain' },
                { name: 'JavaScript (ES6+)', level: 80, category: 'Frontend Development', icon: 'devicon-javascript-plain' },
                { name: 'TypeScript', level: 80, category: 'Frontend Development', icon: 'devicon-typescript-plain' },
                { name: 'Angular 16+', level: 80, category: 'Frontend Development', icon: 'devicon-angular-plain' },
            ],
        },
        {
            name: 'DevOps & Cloud',
            icon: 'fa-cloud',
            skills: [
                { name: 'Docker', level: 75, category: 'DevOps & Cloud', icon: 'devicon-docker-plain' },
                { name: 'Git', level: 85, category: 'DevOps & Cloud', icon: 'devicon-git-plain' },
            ],
        },
        {
            name: 'Databases',
            icon: 'fa-database',
            skills: [
                { name: 'PostgreSQL', level: 80, category: 'Databases', icon: 'devicon-postgresql-plain' },
                { name: 'Microsoft SQL Server', level: 75, category: 'Databases', icon: 'devicon-microsoftsqlserver-plain' },
                { name: 'Oracle PL/SQL', level: 70, category: 'Databases', icon: 'devicon-oracle-plain' },
                { name: 'Redis', level: 65, category: 'Databases', icon: 'devicon-redis-plain' },
                { name: 'Entity Framework Core', level: 80, category: 'Databases', icon: 'fa-layer-group' },
            ],
        },
        {
            name: 'Software Architecture',
            icon: 'fa-sitemap',
            skills: [
                { name: 'N-Tier Architecture', level: 80, category: 'Software Architecture', icon: 'fa-layer-group' },
                { name: 'Onion Architecture', level: 75, category: 'Software Architecture', icon: 'fa-cube' },
                { name: 'SOLID Principles', level: 80, category: 'Software Architecture', icon: 'fa-puzzle-piece' },
                { name: 'Design Patterns', level: 75, category: 'Software Architecture', icon: 'fa-sitemap' },
            ],
        },
    ],

    contact: {
        email: 'kartemre3403@gmail.com',
        social: {
            github: 'https://github.com/kartemre',
            linkedin: 'https://www.linkedin.com/in/emre-kart',
            website: 'https://emrekart.me',
        },
    },
};
